# generate the filesystem for the web server
# based on ipython 1.1

IPYTHON=ipython/html
FILESYS=filesys-1.1

mkdir -p $FILESYS/static/auth/js
mkdir -p $FILESYS/static/base/images
mkdir -p $FILESYS/static/base/js
mkdir -p $FILESYS/static/components/bootstrap/bootstrap/js
mkdir -p $FILESYS/static/components/codemirror/addon/comment
mkdir -p $FILESYS/static/components/codemirror/addon/edit
mkdir -p $FILESYS/static/components/codemirror/addon/mode
mkdir -p $FILESYS/static/components/codemirror/lib
mkdir -p $FILESYS/static/components/codemirror/mode/css
mkdir -p $FILESYS/static/components/codemirror/mode/gfm
mkdir -p $FILESYS/static/components/codemirror/mode/htmlmixed
mkdir -p $FILESYS/static/components/codemirror/mode/javascript
mkdir -p $FILESYS/static/components/codemirror/mode/markdown
mkdir -p $FILESYS/static/components/codemirror/mode/python
mkdir -p $FILESYS/static/components/codemirror/mode/rst
mkdir -p $FILESYS/static/components/codemirror/mode/xml
mkdir -p $FILESYS/static/components/font-awesome/build/assets/font-awesome/font
mkdir -p $FILESYS/static/components/highlight.js/build
mkdir -p $FILESYS/static/components/jquery
mkdir -p $FILESYS/static/components/jquery-ui/themes/smoothness/images
mkdir -p $FILESYS/static/components/jquery-ui/ui/minified
mkdir -p $FILESYS/static/components/marked/lib
mkdir -p $FILESYS/static/components/requirejs
mkdir -p $FILESYS/static/custom
mkdir -p $FILESYS/static/dateformat
mkdir -p $FILESYS/static/notebook/css
mkdir -p $FILESYS/static/notebook/js
mkdir -p $FILESYS/static/notebook/js/celltoolbarpresets
mkdir -p $FILESYS/static/services/kernels/js
mkdir -p $FILESYS/static/style
mkdir -p $FILESYS/static/tree/css
mkdir -p $FILESYS/static/tree/js


cp $IPYTHON/static/components/font-awesome/build/assets/font-awesome/font/fontawesome-webfont.woff $FILESYS/static/components/font-awesome/build/assets/font-awesome/font/fontawesome-webfont.woff
cp $IPYTHON/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css                        $FILESYS/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css 
cp $IPYTHON/static/style/style.min.css                                                             $FILESYS/static/style/style.min.css 
cp $IPYTHON/static/tree/css/override.css                                                           $FILESYS/static/tree/css/override.css 
cp $IPYTHON/static/custom/custom.css                                                               $FILESYS/static/custom/custom.css 
cp $IPYTHON/static/components/requirejs/require.js                                                 $FILESYS/static/components/requirejs/require.js 
cp $IPYTHON/static/base/images/ipynblogo.png                                                       $FILESYS/static/base/images/ipynblogo.png 
cp $IPYTHON/static/components/jquery/jquery.min.js                                                 $FILESYS/static/components/jquery/jquery.min.js 
cp $IPYTHON/static/components/jquery-ui/ui/minified/jquery-ui.min.js                               $FILESYS/static/components/jquery-ui/ui/minified/jquery-ui.min.js 
cp $IPYTHON/static/components/bootstrap/bootstrap/js/bootstrap.min.js                              $FILESYS/static/components/bootstrap/bootstrap/js/bootstrap.min.js 
cp $IPYTHON/static/base/js/page.js                                                                 $FILESYS/static/base/js/page.js 
cp $IPYTHON/static/base/js/namespace.js                                                            $FILESYS/static/base/js/namespace.js 
cp $IPYTHON/static/auth/js/loginwidget.js                                                          $FILESYS/static/auth/js/loginwidget.js 
cp $IPYTHON/static/base/js/dialog.js                                                               $FILESYS/static/base/js/dialog.js 
cp $IPYTHON/static/tree/js/notebooklist.js                                                         $FILESYS/static/tree/js/notebooklist.js 
cp $IPYTHON/static/tree/js/clusterlist.js                                                          $FILESYS/static/tree/js/clusterlist.js 
cp $IPYTHON/static/custom/custom.js                                                                $FILESYS/static/custom/custom.js 
cp $IPYTHON/static/tree/js/main.js                                                                 $FILESYS/static/tree/js/main.js 
cp $IPYTHON/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css                        $FILESYS/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css 
cp $IPYTHON/static/components/codemirror/lib/codemirror.css                                        $FILESYS/static/components/codemirror/lib/codemirror.css 
cp $IPYTHON/static/style/style.min.css                                                             $FILESYS/static/style/style.min.css 
cp $IPYTHON/static/notebook/css/override.css                                                       $FILESYS/static/notebook/css/override.css 
cp $IPYTHON/static/components/requirejs/require.js                                                 $FILESYS/static/components/requirejs/require.js 
cp $IPYTHON/static/custom/custom.css                                                               $FILESYS/static/custom/custom.css 
cp $IPYTHON/static/components/jquery/jquery.min.js                                                 $FILESYS/static/components/jquery/jquery.min.js 
cp $IPYTHON/static/components/jquery-ui/ui/minified/jquery-ui.min.js                               $FILESYS/static/components/jquery-ui/ui/minified/jquery-ui.min.js 
cp $IPYTHON/static/components/bootstrap/bootstrap/js/bootstrap.min.js                              $FILESYS/static/components/bootstrap/bootstrap/js/bootstrap.min.js 
cp $IPYTHON/static/base/js/namespace.js                                                            $FILESYS/static/base/js/namespace.js 
cp $IPYTHON/static/base/js/page.js                                                                 $FILESYS/static/base/js/page.js 
cp $IPYTHON/static/auth/js/loginwidget.js                                                          $FILESYS/static/auth/js/loginwidget.js 
cp $IPYTHON/static/base/images/ipynblogo.png                                                       $FILESYS/static/base/images/ipynblogo.png 
cp $IPYTHON/static/components/codemirror/lib/codemirror.js                                         $FILESYS/static/components/codemirror/lib/codemirror.js 
cp $IPYTHON/static/components/codemirror/addon/mode/loadmode.js                                    $FILESYS/static/components/codemirror/addon/mode/loadmode.js 
cp $IPYTHON/static/components/codemirror/addon/mode/multiplex.js                                   $FILESYS/static/components/codemirror/addon/mode/multiplex.js 
cp $IPYTHON/static/components/codemirror/addon/comment/comment.js                                  $FILESYS/static/components/codemirror/addon/comment/comment.js 
cp $IPYTHON/static/components/codemirror/addon/mode/overlay.js                                     $FILESYS/static/components/codemirror/addon/mode/overlay.js 
cp $IPYTHON/static/components/codemirror/addon/edit/matchbrackets.js                               $FILESYS/static/components/codemirror/addon/edit/matchbrackets.js 
cp $IPYTHON/static/components/codemirror/mode/htmlmixed/htmlmixed.js                               $FILESYS/static/components/codemirror/mode/htmlmixed/htmlmixed.js 
cp $IPYTHON/static/components/codemirror/mode/xml/xml.js                                           $FILESYS/static/components/codemirror/mode/xml/xml.js 
cp $IPYTHON/static/components/codemirror/mode/javascript/javascript.js                             $FILESYS/static/components/codemirror/mode/javascript/javascript.js 
cp $IPYTHON/static/components/codemirror/mode/css/css.js                                           $FILESYS/static/components/codemirror/mode/css/css.js 
cp $IPYTHON/static/components/codemirror/mode/rst/rst.js                                           $FILESYS/static/components/codemirror/mode/rst/rst.js 
cp $IPYTHON/static/components/codemirror/mode/gfm/gfm.js                                           $FILESYS/static/components/codemirror/mode/gfm/gfm.js 
cp $IPYTHON/static/components/codemirror/mode/python/python.js                                     $FILESYS/static/components/codemirror/mode/python/python.js 
cp $IPYTHON/static/components/codemirror/mode/markdown/markdown.js                                 $FILESYS/static/components/codemirror/mode/markdown/markdown.js 
cp $IPYTHON/static/components/highlight.js/build/highlight.pack.js                                 $FILESYS/static/components/highlight.js/build/highlight.pack.js 
cp $IPYTHON/static/notebook/js/codemirror-ipython.js                                               $FILESYS/static/notebook/js/codemirror-ipython.js 
cp $IPYTHON/static/dateformat/date.format.js                                                       $FILESYS/static/dateformat/date.format.js 
cp $IPYTHON/static/base/js/events.js                                                               $FILESYS/static/base/js/events.js 
cp $IPYTHON/static/base/js/dialog.js                                                               $FILESYS/static/base/js/dialog.js 
cp $IPYTHON/static/notebook/js/layoutmanager.js                                                    $FILESYS/static/notebook/js/layoutmanager.js 
cp $IPYTHON/static/base/js/utils.js                                                                $FILESYS/static/base/js/utils.js 
cp $IPYTHON/static/notebook/js/mathjaxutils.js                                                     $FILESYS/static/notebook/js/mathjaxutils.js 
cp $IPYTHON/static/notebook/js/outputarea.js                                                       $FILESYS/static/notebook/js/outputarea.js 
cp $IPYTHON/static/notebook/js/cell.js                                                             $FILESYS/static/notebook/js/cell.js 
cp $IPYTHON/static/notebook/js/celltoolbar.js                                                      $FILESYS/static/notebook/js/celltoolbar.js 
cp $IPYTHON/static/notebook/js/codecell.js                                                         $FILESYS/static/notebook/js/codecell.js 
cp $IPYTHON/static/notebook/js/completer.js                                                        $FILESYS/static/notebook/js/completer.js 
cp $IPYTHON/static/notebook/js/pager.js                                                            $FILESYS/static/notebook/js/pager.js 
cp $IPYTHON/static/notebook/js/quickhelp.js                                                        $FILESYS/static/notebook/js/quickhelp.js 
cp $IPYTHON/static/notebook/js/textcell.js                                                         $FILESYS/static/notebook/js/textcell.js 
cp $IPYTHON/static/services/kernels/js/kernel.js                                                   $FILESYS/static/services/kernels/js/kernel.js 
cp $IPYTHON/static/notebook/js/savewidget.js                                                       $FILESYS/static/notebook/js/savewidget.js 
cp $IPYTHON/static/notebook/js/menubar.js                                                          $FILESYS/static/notebook/js/menubar.js 
cp $IPYTHON/static/notebook/js/toolbar.js                                                          $FILESYS/static/notebook/js/toolbar.js 
cp $IPYTHON/static/notebook/js/maintoolbar.js                                                      $FILESYS/static/notebook/js/maintoolbar.js 
cp $IPYTHON/static/notebook/js/notebook.js                                                         $FILESYS/static/notebook/js/notebook.js 
cp $IPYTHON/static/notebook/js/notificationwidget.js                                               $FILESYS/static/notebook/js/notificationwidget.js 
cp $IPYTHON/static/notebook/js/notificationarea.js                                                 $FILESYS/static/notebook/js/notificationarea.js 
cp $IPYTHON/static/notebook/js/tooltip.js                                                          $FILESYS/static/notebook/js/tooltip.js 
cp $IPYTHON/static/notebook/js/main.js                                                             $FILESYS/static/notebook/js/main.js 
cp $IPYTHON/static/notebook/js/celltoolbarpresets/default.js                                       $FILESYS/static/notebook/js/celltoolbarpresets/default.js 
cp $IPYTHON/static/notebook/js/contexthint.js                                                      $FILESYS/static/notebook/js/contexthint.js 
cp $IPYTHON/static/notebook/js/config.js                                                           $FILESYS/static/notebook/js/config.js 
cp $IPYTHON/static/notebook/js/celltoolbarpresets/slideshow.js                                     $FILESYS/static/notebook/js/celltoolbarpresets/slideshow.js 
cp $IPYTHON/static/custom/custom.js                                                                $FILESYS/static/custom/custom.js 
cp $IPYTHON/static/components/marked/lib/marked.js                                                 $FILESYS/static/components/marked/lib/marked.js 
cp $IPYTHON/static/components/jquery-ui/themes/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png   $FILESYS/static/components/jquery-ui/themes/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png 
